# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: ""
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00" # This is UTC time (12:30 IST is approximately 07:00 UTC)
      timezone: "Asia/Kolkata" # Setting to Indian timezone
    open-pull-requests-limit: 10
